[build-system]
requires = [
    "scikit-build-core>=0.11.6",
    "nanobind>=2.11.0"
]
build-backend = "scikit_build_core.build"

[project]
name = "fuzzydr-viewer"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy"
]

[tool.scikit-build]
build.verbose = true
wheel.packages = ["python/fuzzydr_viewer"]
